# Generated by Django 5.2.17 on 2026-08-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerprofile_referral_code_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
    ]
