# Generated by Django 5.2.17 on 2026-09-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REFERRAL_REWARD', 'Referral Reward'), ('MILESTONE_BONUS', 'Milestone Bonus'), ('PURCHASE_DEDUCTION', 'Purchase Deduction'), ('REFUND', 'Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('PURCHASE_CASHBACK', 'Purchase Cashback')], max_length=30),
        ),
    ]
