# Generated by Django 5.2.17 on 2026-09-08 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delivery_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeliveryPartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Motorcycle / Bike'), ('Scooter', 'Scooter'), ('Bicycle', 'Bicycle'), ('Van', 'Delivery Van / Auto')], default='Bike', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
