# Generated by Django 5.2.17 on 2026-09-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_delivery_partner_deliverypartnerprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_tx_created_idx'),
        ),
    ]
