# Generated by Django 5.2.17 on 2026-10-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_options_alter_user_is_customer_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', '-is_default', '-created_at'], name='addr_user_def_created_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_customer', '-date_joined'], name='user_cust_date_idx'),
        ),
    ]
