# Generated by Django 5.2.17 on 2026-09-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notif_user_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ORDER', 'Order Update'), ('PROMO', 'Offer / Promotion'), ('WALLET', 'Wallet & Payments'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
