# Generated by Django 5.2.17 on 2026-08-16 10:20

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=orders.models.order_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
