# Generated by Django 5.2.17 on 2026-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packaging_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
