# Generated by Django 5.2.17 on 2026-08-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer_note_order_owner_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
