# Generated by Django 5.2.17 on 2026-08-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_latitude_order_delivery_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready for pickup'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='NEW', max_length=12),
        ),
    ]
