# Generated by Django 5.2.17 on 2026-09-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_slot_date_order_delivery_slot_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashback_credited',
            field=models.BooleanField(default=False),
        ),
    ]
