# Generated by Django 5.2.17 on 2026-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
