# Generated by Django 5.2.17 on 2026-09-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'display_order'], name='prod_cat_act_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='prod_created_at_idx'),
        ),
    ]
