# Generated by Django 5.2.17 on 2026-10-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_prod_cat_act_ord_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_active_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='prod_cat_act_ord_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'display_order', '-created_at'], name='prod_act_ord_date_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'display_order', '-created_at'], name='prod_cat_act_ord_date_idx'),
        ),
    ]
