# Generated by Django 5.2.17 on 2026-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Smart Kirana', max_length=100)),
                ('is_open', models.BooleanField(default=True, help_text='Turn off to temporarily stop accepting orders')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('packaging_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert when stock falls below this number')),
                ('delivery_mode', models.CharField(choices=[('PICKUP', 'Store Pickup Only'), ('DELIVERY', 'Delivery Only'), ('BOTH', 'Both')], default='PICKUP', max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('auto_accept_orders', models.BooleanField(default=False, help_text='Automatically accept new orders')),
            ],
        ),
    ]
