# Generated by Django 5.2.17 on 2026-08-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='invoice_signature',
            field=models.ImageField(blank=True, help_text='Upload a signature image with a white or transparent background.', null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(default='Narendra Kirana', max_length=100),
        ),
    ]
