# Generated by Django 5.2.17 on 2026-08-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storesettings_invoice_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='store_address',
            field=models.TextField(blank=True, default='123 Market Street, City Center'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_email',
            field=models.EmailField(blank=True, default='support@narendrakirana.in', max_length=254),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_phone',
            field=models.CharField(blank=True, default='+91 98765 43210', max_length=20),
        ),
    ]
