# Generated by Django 5.2.17 on 2026-08-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='great_deals_title',
            field=models.CharField(default='Great Deals', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='new_arrivals_title',
            field=models.CharField(default='New Arrivals', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='popular_picks_title',
            field=models.CharField(default='Popular picks', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_great_deals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_new_arrivals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_popular_picks',
            field=models.BooleanField(default=True),
        ),
    ]
