# Generated by Django 5.2.17 on 2026-08-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_display_order_product_display_order'),
        ('store', '0005_storesettings_great_deals_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('popular_picks', 'Popular Picks'), ('great_deals', 'Great Deals'), ('new_arrivals', 'New Arrivals')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_sections', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_products', to='store.homepagesection')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('section', 'product')},
            },
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='products',
            field=models.ManyToManyField(blank=True, through='store.HomepageSectionProduct', to='products.product'),
        ),
    ]
