# Generated by Django 5.2.17 on 2026-08-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_homepagesection_homepagesectionproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='homepage_section_order',
            field=models.CharField(default='popular_picks,great_deals,new_arrivals', max_length=200),
        ),
    ]
