# Generated by Django 5.2.17 on 2026-08-17 11:03

from django.db import migrations, models

def migrate_sections(apps, schema_editor):
    HomepageSection = apps.get_model('store', 'HomepageSection')
    StoreSettings = apps.get_model('store', 'StoreSettings')
    
    settings = StoreSettings.objects.first()
    if not settings:
        return
        
    order_str = settings.homepage_section_order or "popular_picks,great_deals,new_arrivals"
    order_list = [k.strip() for k in order_str.split(',') if k.strip()]
    
    titles = {
        'popular_picks': settings.popular_picks_title or 'Popular Picks',
        'great_deals': settings.great_deals_title or 'Great Deals',
        'new_arrivals': settings.new_arrivals_title or 'New Arrivals',
    }
    
    visibilities = {
        'popular_picks': settings.show_popular_picks,
        'great_deals': settings.show_great_deals,
        'new_arrivals': settings.show_new_arrivals,
    }
    
    for section in HomepageSection.objects.all():
        key = section.section_key
        section.title = titles.get(key, key.replace('_', ' ').title())
        section.is_active = visibilities.get(key, True)
        if key in order_list:
            section.display_order = order_list.index(key)
        else:
            section.display_order = 99
        section.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storesettings_homepage_section_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesection',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='title',
            field=models.CharField(default='New Section', max_length=100),
        ),
        migrations.RunPython(migrate_sections, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='homepagesection',
            name='section_key',
        ),
    ]
