# Generated by Django 5.2.17 on 2026-08-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_homepagesection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Google Gemini API Key for Vision', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gemini_vision_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='Groq API Key for Text Generation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='groq_text_model',
            field=models.CharField(default='llama3-8b-8192', max_length=50),
        ),
    ]
