# Generated by Django 5.2.17 on 2026-08-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storesettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='gemini_vision_model',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='groq_api_key',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='groq_text_model',
        ),
    ]
