# Generated by Django 5.2.17 on 2026-08-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_storesettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_bg_color',
            field=models.CharField(default='#ef4444', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
