# Generated by Django 5.2.17 on 2026-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_flashannouncement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashannouncement',
            name='link',
        ),
        migrations.AlterField(
            model_name='flashannouncement',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
