# Generated by Django 5.2.17 on 2026-08-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_flashannouncement_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashAnnouncement',
        ),
    ]
