# Generated by Django 5.2.17 on 2026-08-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_flashannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='banner_link',
            field=models.CharField(blank=True, help_text='Optional URL to navigate to when clicked', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('products', 'Product Grid'), ('banner', 'Mid-Page Banner')], default='products', max_length=20),
        ),
    ]
