# Generated by Django 5.2.17 on 2026-08-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_homepagesection_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='allowed_pincodes',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of allowed pincodes'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='min_delivery_order_amount',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
    ]
