# Generated by Django 5.2.17 on 2026-08-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_storesettings_allowed_pincodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='is_home_delivery_active',
            field=models.BooleanField(default=False),
        ),
    ]
