# Generated by Django 5.2.17 on 2026-09-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_storesettings_is_home_delivery_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail / Google Workspace'), ('outlook', 'Outlook / Office 365'), ('custom', 'Custom SMTP')], default='gmail', max_length=20)),
                ('sender_email', models.EmailField(blank=True, default='', help_text='Email address used to send emails (e.g., your store Gmail)', max_length=254)),
                ('sender_name', models.CharField(default='Narendra Kirana', help_text='Display name on outgoing emails', max_length=100)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('encrypted_app_password', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False, help_text='Enable custom store email sending. If disabled, fallback to server settings.')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
