# Generated by Django 5.2.17 on 2026-09-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_storeemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='announcement_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_text',
            field=models.TextField(blank=True, default='🎉 Free Home Delivery on orders above ₹499! Use code FIRST50 for ₹50 off on first order.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='app_update_message',
            field=models.CharField(default='A new and improved version of Narendra Kirana is available. Please update to continue shopping.', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='app_update_url',
            field=models.URLField(blank=True, default='https://play.google.com/store/apps/details?id=com.narendrakirana.app'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='auto_cutoff_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='emergency_pause_message',
            field=models.CharField(blank=True, default='We are currently experiencing high order volume and will resume shortly. Thank you for your patience!', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='enable_announcement_bar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='enable_dynamic_upi_qr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='enable_festive_popup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='enable_itemized_tax_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='enable_time_slots',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='enable_whatsapp_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='festive_popup_content',
            field=models.TextField(blank=True, default='Enjoy huge festive discounts on all grocery essentials. Shop today!'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='festive_popup_image',
            field=models.ImageField(blank=True, null=True, upload_to='festive/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='festive_popup_title',
            field=models.CharField(blank=True, default='Special Festive Offer! 🪔', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='force_app_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='fssai_license_number',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='invoice_terms_and_conditions',
            field=models.TextField(blank=True, default='1. Goods once sold will not be taken back without original bill.\n2. In case of any dispute, local jurisdiction applies.\n3. Perishable goods must be reported within 24 hours.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='is_emergency_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='is_maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='latest_mobile_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='maintenance_estimated_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='We are currently performing scheduled maintenance to serve you better. We will be back online shortly!'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='max_orders_per_slot',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='max_wallet_usage_percentage',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='min_mobile_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='order_cashback_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='preparation_buffer_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='referral_bonus_referee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='referral_bonus_referrer',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='referral_min_order_amount',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_timings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='time_slots_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='upi_payee_name',
            field=models.CharField(blank=True, default='Narendra Kirana', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='upi_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qr/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_default_message',
            field=models.CharField(default='Hi Narendra Kirana, I need help with my grocery order.', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='+919876543210', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_order_help_template',
            field=models.CharField(default='Hi Narendra Kirana, I need help with Order #{order_id}', max_length=255),
        ),
    ]
