# Generated by Django 5.2.17 on 2026-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_storesettings_announcement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='app_download_btn_text',
            field=models.CharField(blank=True, default='Download APK', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='app_icon',
            field=models.ImageField(blank=True, null=True, upload_to='app_icon/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='app_name',
            field=models.CharField(blank=True, default='Narendra Kirana', max_length=100),
        ),
    ]
