# Generated by Django 5.2.17 on 2026-09-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_storesettings_app_download_btn_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='app_update_url',
            field=models.URLField(blank=True, default='https://github.com/saisatyanarayana09/narendra-kirana/releases/latest/download/narendra-kirana.apk'),
        ),
    ]
