# Generated by Django 5.2.17 on 2026-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_storesettings_app_update_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Maximum home delivery radius in kilometers', max_digits=5),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=17.385044, help_text='Store latitude for GPS & maps', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=78.486671, help_text='Store longitude for GPS & maps', max_digits=9, null=True),
        ),
    ]
