# Generated by Django 5.2.17 on 2026-09-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_storesettings_delivery_radius_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='enforce_delivery_radius',
            field=models.BooleanField(default=False, help_text='Block checkout if customer address is beyond delivery radius'),
        ),
    ]
