# Generated by Django 5.2.17 on 2026-09-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_storesettings_enforce_delivery_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='popular_searches',
            field=models.TextField(blank=True, default='Aashirvaad Shudh Chakki Atta\nFresh Paneer & Milk\nFortune Sunflower Oil\nBasmati Rice & Dals\nTata Salt & Spices', help_text='One search term per line to show in the search bar ticker.'),
        ),
    ]
