# Generated by Django 5.2.17 on 2026-10-04 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_product_active_order_idx_and_more'),
        ('store', '0023_storesettings_popular_searches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='feedback_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='homepagesectionproduct',
            index=models.Index(fields=['section', 'position'], name='hsp_section_pos_idx'),
        ),
    ]
