# Generated by Django 5.2.17 on 2026-10-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='delivery_app_update_url',
            field=models.URLField(blank=True, default='https://github.com/saisatyanarayana09/narendra-kirana/releases/download/delivery-latest/narendra-kirana-delivery.apk'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='owner_app_update_url',
            field=models.URLField(blank=True, default='https://github.com/saisatyanarayana09/narendra-kirana/releases/download/owner-latest/narendra-kirana-owner.apk'),
        ),
    ]
