# Generated by Django 5.2.17 on 2026-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
