# Generated by Django 5.2.17 on 2026-08-16 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_banner_display_order'),
        ('products', '0005_category_display_order_product_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='applicable_category',
            field=models.ForeignKey(blank=True, help_text='If set, discount only applies to items in this category', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
