# Generated by Django 5.2.17 on 2026-08-18 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_promocode_applicable_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_referrals', models.PositiveIntegerField(help_text='Number of successful referrals needed to unlock this bonus', unique=True)),
                ('bonus_reward', models.DecimalField(decimal_places=2, help_text='Bonus amount credited to the wallet', max_digits=10)),
            ],
            options={
                'ordering': ['required_referrals'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('referrer_reward', models.DecimalField(decimal_places=2, default=50.0, help_text='Amount given to the person whose code was used', max_digits=10)),
                ('referee_reward', models.DecimalField(decimal_places=2, default=50.0, help_text='Amount given to the new user who signs up', max_digits=10)),
                ('share_text_template', models.TextField(default='I buy my groceries from Narendra Kirana! Use my referral code {code} to get ₹{reward} instantly in your wallet! Shop now: {link}')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending First Order'), ('COMPLETED', 'Completed & Rewarded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
