# Generated by Django 5.2.17 on 2026-08-18 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_referralmilestone_referralsettings_referral'),
        ('products', '0005_category_display_order_product_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsettings',
            name='min_spend_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='min_spend_period',
            field=models.CharField(choices=[('WEEK', 'Past 7 Days'), ('MONTH', 'Past 30 Days'), ('YEAR', 'Past 365 Days')], default='MONTH', max_length=10),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='referrer_reward_product',
            field=models.ForeignKey(blank=True, help_text='Specific product to give as an additional reward', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='referralsettings',
            name='require_min_spend',
            field=models.BooleanField(default=False, help_text='Require referrer to meet a minimum spend before they can earn rewards'),
        ),
    ]
