# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_referralsettings_min_spend_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending First Order'),
                    ('READY_TO_CLAIM', 'Ready to Claim'),
                    ('AWAITING_APPROVAL', 'Awaiting Owner Approval'),
                    ('COMPLETED', 'Completed & Rewarded'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
