# Generated by Django 5.2.17 on 2026-09-16 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_promocode_max_uses_per_user_promousage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', '-created_at'], name='referral_ref_created_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_user', '-created_at'], name='referral_refu_created_idx'),
        ),
    ]
