# Generated by Django 5.2.17 on 2026-09-24 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_referral_referral_ref_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='promousage',
            index=models.Index(fields=['promo_code', 'user'], name='promo_usage_pu_idx'),
        ),
    ]
