# Generated by Django 5.2.17 on 2026-10-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_promousage_promo_usage_pu_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active', 'display_order', '-created_at'], name='banner_act_ord_date_idx'),
        ),
    ]
