# Generated by Django 5.2.17 on 2026-10-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_alter_banner_options_banner_banner_act_ord_date_idx'),
        ('products', '0010_remove_product_product_active_order_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', '-created_at'], name='promo_act_created_idx'),
        ),
    ]
