from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model

User = get_user_model()

class Command(BaseCommand):
    help = 'Cleans up all AI test accounts and their associated data (Orders, Addresses, etc.)'

    def handle(self, *args, **kwargs):
        # Find all users generated by the AI testing scripts
        ai_users = User.objects.filter(email__icontains='ai_test')
        
        count = ai_users.count()
        if count == 0:
            self.stdout.write(self.style.SUCCESS('No AI test accounts found. Database is clean.'))
            return

        self.stdout.write(self.style.WARNING(f'Found {count} AI test accounts. Deleting...'))
        
        from orders.models import Order
        
        # Because of Django's foreign key protection on Orders, we must delete orders explicitly first
        Order.objects.filter(customer__in=ai_users).delete()
        
        ai_users.delete()
        
        self.stdout.write(self.style.SUCCESS(f'Successfully deleted {count} AI test accounts and all their traces from the database.'))
